language: python
python:
  - "3.6"

cache:
  directories:
    - "~/.platformio"

env:
  - EXAMPLE=examples/ble
  - EXAMPLE=examples/button-dash
  - EXAMPLE=examples/button
  - EXAMPLE=examples/buzzer
  - EXAMPLE=examples/gateway
  - EXAMPLE=examples/ir
  - EXAMPLE=examples/led-matrix
  - EXAMPLE=examples/led-rgb
  - EXAMPLE=examples/led
  - EXAMPLE=examples/pir

install:
  - pip install -U platformio
  - pio update
  - touch examples/gateway/include/secrets.h
  - export PLATFORMIO_BUILD_FLAGS="'-DBRICKS_GATEWAY_MAC=\"00:00:00:00:00:00\"'"
  - export PLATFORMIO_LIBDEPS_DIR="~/.platformio"

script:
  - pio run --target "" --project-dir $EXAMPLE
