language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
  directories:
    - "~/.platformio"

env:
  - EXAMPLE=examples/ble
  - EXAMPLE=examples/button-dash
  - EXAMPLE=examples/button
  - EXAMPLE=examples/buzzer
  - EXAMPLE=examples/gateway
  - EXAMPLE=examples/ir
  - EXAMPLE=examples/led-matrix
  - EXAMPLE=examples/led-rgb
  - EXAMPLE=examples/led
  - EXAMPLE=examples/pir

install:
  - pip install -U platformio
  - pio update
  - export PLATFORMIO_BUILD_FLAGS="'-DBRICKS_GATEWAY_MAC=\"00:00:00:00:00:00\"'"

script:
  - cd $EXAMPLE
  - pio run --target ""
