version: "2.1"

volumes:
  resin-data:

services:
  node-red:
    build: .
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "80:1880"
    networks:
      - node-red-net
    volumes:
      - resin-data:/data
    links:
      - "mqtt:mqtt"

  mqtt:
    image: eclipse-mosquitto:1.6.13
    ports:
      - "1883:1883"
    networks:
      - node-red-net

networks:
  node-red-net:
